### ISSUE TITLE
ESS Support

### ISSUE THREAD

**Issue by jeswr** [NoelDeMartin/umai#6] opened 2023-01-23 23:30 UTC
Very nice work! In particular I wanted to highlight that you have great interfaces error handling in Solid.

I have tried this against ESS and CSS. Against CSS this runs very smoothly; but when I try and use this with an ESS instance (using PodSpaces https://login.inrupt.com/) then I get the "Something went wrong" page with the error.

```
Error: User profile went missing

refreshUserProfile@https://umai.noeldemartin.com/assets/main.952338c0.js:113:302948
```

I clicked the "Send Error Report" button so hopefully that means you also recieved something in sentry.

I also tried clicking "Report in GitHub" but that just seems to redirect back around to the "Something went wrong!" page after a few redirects.

**Comment by NoelDeMartin** [comment] 2023-01-24 06:02
Hey, thanks for reporting an issue! Unfortunately, I cannot reproduce most of your problems :/.

I just tried with an account in `login.inrupt.com` and it works fine for me. That error is thrown when fetching the webId of the user doesn't work, maybe you can look at the network requests to see if you get any details why that's happening? Also try in a different browser or clearing the cache. If that still doesn't work, I'm not sure what's going on so I'll need more details to reproduce it. I'll try to add more debugging information for that error though.

About the github url, it does work for me so I'm not sure why you're getting a redirect. If you get it again, can you share the url you're getting? That "Report in Github" button is a link, so you should be able to copy the url before visiting it.

And finally, the "Send Error Report" button seems to be throwing a CORS error! So I'll have to look into that, thanks for letting me know.

**Comment by jeswr** [comment] 2023-01-24 06:56
I was able to get this working on a fresh account. The account that was failing is one that I have have been using as a test account for a while and so has quite a bit written to it. The console error I am getting is

![image](https://user-images.githubusercontent.com/63333554/214226523-7c3df5de-0041-4c2e-bc43-a708957e4c9f.png)

and the contents of the profile card are

```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix vcard: <http://www.w3.org/2006/vcard/ns#> .

<https://storage.ap.inrupt.com/d8d9151a-9eaa-4a31-82be-be459700e632/profile>
        a                  foaf:Document ;
        foaf:maker         <https://id.inrupt.com/jeswrtest51> ;
        foaf:primaryTopic  <https://id.inrupt.com/jeswrtest51> .

<https://id.inrupt.com/jeswrtest51>
        vcard:hasPhoto <https://avatars.githubusercontent.com/u/63333554?v=4> ;
        a       <http://schema.org/Person> .
```

The 406 indicates that I may have accidentally converted the profile card to have a `content/octet-stream` type testing using another application which could be the cause of the problem. I'll double check that when I get the chance and re-open the issue if I am wrong.

> Github URL

The following is the github url I get; I get the same circular flow in Firefox and Chrome. I see the `?code=...` appear in my url during the series of redirects so it seems to be trying to log back in at some point.

https://umai.noeldemartin.com/issues/new?title=Error%3A%20User%20profile%20went%20missing&body=%5BPlease%2C%20explain%20here%20what%20you%20were%20trying%20to%20do%20when%20this%20error%20appeared%5D%0A%0AError%20details%3A%0A%60%60%60%0AError%3A%20User%20profile%20went%20missing%0A%20%20%20%20at%20Proxy.refreshUserProfile%20(https%3A%2F%2Fumai.noeldemartin.com%2Fassets%2Fmain.952338c0.js%3A113%3A302948)%0A%20%20%20%20at%20async%20onSessionStarted%20(https%3A%2F%2Fumai.noeldemartin.com%2Fassets%2Fmain.952338c0.js%3A113%3A307095)%0A%20%20%20%20at%20async%20https%3A%2F%2Fumai.noeldemartin.com%2Fassets%2Fmain.952338c0.js%3A113%3A300153%0A%20%20%20%20at%20async%20Promise.all%20(index%200)%0A%20%20%20%20at%20async%20Ak.inrupt.notifyListeners%20(https%3A%2F%2Fumai.noeldemartin.com%2Fassets%2Fmain.952338c0.js%3A113%3A300082)%0A%20%20%20%20at%20async%20Ak.inrupt.startSession%20(https%3A%2F%2Fumai.noeldemartin.com%2Fassets%2Fmain.952338c0.js%3A113%3A299864)%0A%20%20%20%20at%20async%20Ak.inrupt.loginFromRedirect%20(https%3A%2F%2Fumai.noeldemartin.com%2Fassets%2Fmain.952338c0.js%3A113%3A302209)%0A%20%20%20%20at%20async%20Ak.inrupt.restoreSession%20(https%3A%2F%2Fumai.noeldemartin.com%2Fassets%2Fmain.952338c0.js%3A113%3A301920)%0A%20%20%20%20at%20async%20Ak.inrupt.boot%20(https%3A%2F%2Fumai.noeldemartin.com%2Fassets%2Fmain.952338c0.js%3A113%3A299635)%0A%20%20%20%20at%20async%20Proxy.bootAuthenticator%20(https%3A%2F%2Fumai.noeldemartin.com%2Fassets%2Fmain.952338c0.js%3A113%3A307414)%0A%60%60%60

**Comment by jeswr** [comment] 2023-01-27 06:36
Can confirm the problem was the content type of the profile being `application/octet-stream`

**Comment by NoelDeMartin** [comment] 2023-03-11 08:23
Hey, thanks again for reporting the issue. I've fixed the "report to github" url, and improved some of the error reporting. I'm closing the issue for now, let me know if you find anything else!

**Closed by NoelDeMartin** 2023-03-11 08:23 UTC
Labels: bug
